Repository pagopa/cgn-onboarding-portal-infra, pull requests merged in 2021-05, with the labels that each got.

#15 Add container with spid test env
  README.md
  code/.terraform.lock.hcl
  code/README.md
  code/api.tf
  code/modules/storage_account/README.md
  code/spid_testenv.tf
  code/spid_testenv_conf/config.yaml.tpl
  vars/README.md
  vars/dev.tf
  vars/uat.tf
Labels: applied

#17 Spid login APIM
  code/README.md
  code/api.tf
  code/cdn.tf
  code/main.tf
  code/outputs.tf
  code/public.tf
  code/spid_testenv.tf
  code/spidlogin_api/policy.xml
  code/spidlogin_api/swagger.json
  code/variables.tf
  vars/dev.tf
  vars/prod.tf
  vars/uat.tf
Labels: applied, no-merge

#18 Add env vars for spid login and validate-jwt policy
  README.md
  code/.terraform.lock.hcl
  code/README.md
  code/api.tf
  code/backend_api/policy.xml
  code/cdn.tf
  code/dns.tf
  code/main.tf
  code/outputs.tf
  code/redis_cache.tf
  code/security.tf
  code/variables.tf
  vars/README.md
  vars/prod.tf
  vars/uat.tf
Labels: applied

#20 Fix typo key
  code/security.tf
Labels: applied

#26 [CGN-19] Key Vault access policy for-cert-renew
  code/README.md
  code/security.tf
  code/variables.tf
  vars/.terraform.lock.hcl
  vars/README.md
  vars/uat.tf
Labels: applied

#27 Add operator search function
  code/.terraform-version
  code/api.tf
  code/modules/app_function/main.tf
  code/modules/app_function/variables.tf
  code/network.tf
  code/variables.tf
  vars/dev.tf
Labels: applied

#31 [#IOINFRA-81] Remove application_id in cert_renew_policy
  code/modules/app_function/main.tf
  code/security.tf
  code/variables.tf
Labels: applied

#32 Add new env var and policy
  code/api.tf
  code/spidlogin_api/policy.xml
Labels: applied

#36 Disable Mail Health check till properly configured
  code/api.tf
Labels: applied

#38 Update swagger and add public api
  code/api.tf
  code/backend_api/swagger.json
  code/backoffice_api/swagger.json
  code/public_api/policy.xml
  code/public_api/swagger.json
Labels: applied

#39 Fix postgres conection uri for APP FUNCTION CGN SEARCH
  code/api.tf
Labels: applied

#40 Add blob storage for ade aa mock
  code/README.md
  code/api.tf
  code/storage.tf
Labels: applied

#37 email setup
  code/api.tf
  code/variables.tf
  vars/dev.tf
Labels: applied, no-merge

#47 Introspect jwt
  code/api.tf
  code/backend_api/policy.xml
  code/backend_api/policy.xml.tpl
Labels: applied

#46 Internal spid - ade aa connection and subscription required for apim ade aa api
  code/api.tf
Labels: applied

#49 Fix Org Issuer on exposed metadata
  code/api.tf
Labels: applied

#50 Add monitor alerts and remove sonarqube
  .pre-commit-config.yaml
  code/README.md
  code/letsencrypt.tf
  code/modules/app_service/README.md
  code/modules/app_service/outputs.tf
  code/monitor.tf
  code/security.tf
  code/sonarqube.tf
  code/variables.tf
  vars/README.md
  vars/dev.tf
  vars/main.tf
Labels: applied

#51 Recaptcha and geolocation token
  code/README.md
  code/api.tf
  code/backend_api/swagger.json
  code/variables.tf
Labels: question
